#!/bin/bash
cd /Users/lewi/Documents/Vyvoj/OptimalyAI
echo "TERMINAL 2: Basic Tools"
echo "======================="
echo ""
echo "⏳ WAIT for Terminal 1 to complete Phase 2"
echo ""
echo "When Terminal 1 is ready, run these commands:"
echo ""
echo "git checkout -b feature/ai-tools-basic"
echo "git pull origin feature/ai-tools-infrastructure"
echo "code ."
echo ""
echo "Then tell Claude:"
echo "I am working on Terminal 2 from AI_TOOLS_PARALLEL_IMPLEMENTATION.md"